package Vista;

public class FrmColaboradorView extends javax.swing.JFrame {

    public FrmColaboradorView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelEscritorio = new javax.swing.JDesktopPane();
        menuPrincipal = new javax.swing.JMenuBar();
        menuConsultas = new javax.swing.JMenu();
        itConsultaProductos = new javax.swing.JMenuItem();
        itConsultaClientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 550));
        setSize(new java.awt.Dimension(600, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 550));

        panelEscritorio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelEscritorioLayout = new javax.swing.GroupLayout(panelEscritorio);
        panelEscritorio.setLayout(panelEscritorioLayout);
        panelEscritorioLayout.setHorizontalGroup(
            panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        panelEscritorioLayout.setVerticalGroup(
            panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscritorio)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscritorio)
        );

        menuPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        menuPrincipal.setBorder(null);
        menuPrincipal.setForeground(new java.awt.Color(51, 51, 51));
        menuPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuPrincipal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        menuPrincipal.setPreferredSize(new java.awt.Dimension(71, 25));

        menuConsultas.setBackground(new java.awt.Color(3, 137, 57));
        menuConsultas.setBorder(null);
        menuConsultas.setForeground(new java.awt.Color(51, 51, 51));
        menuConsultas.setText("Consultas");
        menuConsultas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        itConsultaProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        itConsultaProductos.setBackground(new java.awt.Color(204, 204, 204));
        itConsultaProductos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        itConsultaProductos.setForeground(new java.awt.Color(51, 51, 51));
        itConsultaProductos.setText("Consultar productos");
        itConsultaProductos.setBorder(null);
        itConsultaProductos.setPreferredSize(new java.awt.Dimension(193, 25));
        itConsultaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itConsultaProductosActionPerformed(evt);
            }
        });
        menuConsultas.add(itConsultaProductos);

        itConsultaClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        itConsultaClientes.setBackground(new java.awt.Color(204, 204, 204));
        itConsultaClientes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        itConsultaClientes.setForeground(new java.awt.Color(51, 51, 51));
        itConsultaClientes.setText("Consultar clientes");
        itConsultaClientes.setBorder(null);
        itConsultaClientes.setPreferredSize(new java.awt.Dimension(193, 25));
        itConsultaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itConsultaClientesActionPerformed(evt);
            }
        });
        menuConsultas.add(itConsultaClientes);

        menuPrincipal.add(menuConsultas);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itConsultaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itConsultaProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itConsultaProductosActionPerformed

    private void itConsultaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itConsultaClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itConsultaClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmColaboradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmColaboradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmColaboradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmColaboradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmColaboradorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem itConsultaClientes;
    public javax.swing.JMenuItem itConsultaProductos;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JMenu menuConsultas;
    public javax.swing.JMenuBar menuPrincipal;
    public javax.swing.JDesktopPane panelEscritorio;
    // End of variables declaration//GEN-END:variables
}
